- name: update apt-get cache
  local_action:  shell ssh -o StrictHostKeyChecking=no ubuntu@{{ ansible_host }} sudo /usr/bin/apt-get update  

      
- name: Install python
  local_action:  shell ssh -o StrictHostKeyChecking=no ubuntu@{{ ansible_host }} sudo /usr/bin/apt-get install -y python  

- name: Set authorized key for "root" user 
  become: true
  become_method: sudo
  authorized_key:
    user: root
    state: present
    manage_dir: yes
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
